---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 3.3.5
  NewCops: enable
  Include:
  - 'Gemfile'
  - 'rakefile'
  - '**/*.rb'

require:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-sequel

# ignore block length where unavoidable (e.g., frameworks using blocks)
Metrics/BlockLength:
  Enabled: true
  Exclude:
  - 'spec/**/*' # Minitest's nested test structure requires large blocks
  - 'rakefile' # Rake namespaces produce large blocks
  - 'app/application/controllers/**/*.rb' # Roda's nested controllers require large blocks


Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: table

Naming/RescuedExceptionsVariableName:
  Enabled: false

Style/HashSyntax:
  Enabled: true
  Exclude:
    - 'rakefile'

Style/SymbolArray:
  Enabled: true
  Exclude:
    - 'rakefile'
    - 'app/infrastructure/database/migrations/*.rb'

Sequel/IrreversibleMigration:
  Enabled: true
  Exclude:
    - 'db/migrations/**/*.rb'