---
# Name your file secrets.yml

development:
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  GOOGLE_MAPS_KEY: your_google_maps_key
  OPENAI_TOKEN: your_open_ai_token
  API_HOST: http://localhost:9090

app_test:
  # Infrastructure
  DB_FILENAME: app/infrastructure/database/local/test.db
  API_HOST: http://localhost:9090

test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  GOOGLE_MAPS_KEY: your_google_maps_key
  OPENAI_TOKEN: your_open_ai_token
  API_HOST: http://localhost:9090

production:
  # Infrastructure
  # - assign DATABASE_URL in production
  GOOGLE_MAPS_KEY: your_google_maps_key
  OPENAI_TOKEN: your_open_ai_token
  API_HOST: http://trailsmith-api
